services:
  - type: web
    name: fastapi-cicd-demo
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    buildFilter:
      paths:
        - "**"
      ignoredPaths:
        - "README.md"
        - "docs/**"
        - ".github/**"
        - "tests/**"
        - "*.md"